### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [divyanshub024/AndroidDraw#5]
Hello! I want to contribute on your project with making logo design. What do you think about it?

Best Regards,
Arslan Şahin
Graphics Designer

**Comment by divyanshub024** [comment]
Hey @Arslanshn , I'm glad to hear that you want to contribute to the project. Feel free to work on the logo design. :+1:

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/1uIpnKO8dhyTQ653ZJWUrulXlHUg4FknZ?usp=sharing
hello I did the logo work I hope you like:)

**Comment by Arslanshn** [comment]
Hi, divyan;-)

**Comment by Arslanshn** [comment]
Hi I wonder what you think about the logo?

**Comment by Arslanshn** [comment]
Hi

**Comment by divyanshub024** [comment]
Hi @Arslanshn !! I really liked the design. But I think colors are bit dull. Can it be improved. What do you say?

**Comment by Arslanshn** [comment]
Of course, what is the suggestion

**Comment by Arslanshn** [comment]
Hello Divyanshu Logo I used different colors.

**Comment by divyanshub024** [comment]
@Arslanshn Thanks a lot!! Looks good. I will apply the logo soon. :+1:

**Comment by Arslanshn** [comment]
I'm glad you like it. Divyanshub:-)

**Comment by Arslanshn** [comment]
Hi, Divyanshu;-)

**Comment by divyanshub024** [comment]
Thanks @Arslanshn for the amazing logo. I have updated the Readme.
